### ISSUE TITLE
Difficult/Impossible to make inbetween poses in some cases

### ISSUE THREAD

**Issue by josephsdaniels** [aldrinsartfactory/stopmagic#8]
Currently, the workflow for making in-between poses can be difficult or impossible.  In the attached scene, try making an in-between pose on frame 20.

- With mesh selected, at frame 20 hit Keyframe Mesh
- It creates a pose, but this is an instance of what is on frame 23 (expected result - creates a unique duplicate of what is on frame 17, because that's the pose that is visible at the time Keyframe Mesh button was pressed)
- Now we're stuck because there doesn't seem to be a way to now make that pose on frame 20 unique from 23. Any edits to 20 also change the pose at frame 23. :(

[HeartBubbles_v02.zip](https://github.com/aldrinsartfactory/stopmagic/files/8056366/HeartBubbles_v02.zip)

**Comment by aldrinmathew** [comment]
This was caused by the function that got the new mesh index looking for the id of the active mesh, instead of all available keyframes. This has been fixed with the help of another function wrote to improve the Onion Skin logic. Two birds with one stone.

**Comment by josephsdaniels** [comment]
Unfortunately, this is still not fixed.  Try duplicating a pose and moving it to another time. It's still impossible to hit Keyframe Mesh to make this a unique pose like we used to be able to do in the previous incarnation of this (Keymesh). This functionality is very important to have, for the following use cases:
-reusing an existing pose but wanting to tweak it slightly, say for making some subtle ease in/out
-making a library of mouth shapes and wanting to use those throughout an anim and also add unique shapes or inbetweens based off the original set.

**Comment by aldrinmathew** [comment]
So I tested the file. But I am not able to reproduce the error in a different file.
During debugging, while scrubbing through the timeline, the only error is
```
TypeError: 'module' object is not callable
```
Can you uninstall the addon, reinstall it and then try creating a new file to see if you can reproduce the issue?

**Comment by josephsdaniels** [comment]
Sure thing. Completely removed, reloaded Blender, re-installed, and I can re-create it every time I try.

Steps to Reproduce:
1. Create new pose on default cube on frame 1.
2. Hit Shift-D to duplicate the key on the timeline and drag it forward.
3. Go to the time of the new pose and hit Keyframe Mesh button. Expectation: It makes a new pose that is a unique copy of the first pose. Result: nothing

The reason this is so important is that sometimes you want to duplicate a few previous poses but then make those duplicates unique. This is currently impossible, to my knowledge.

**Comment by aldrinmathew** [comment]
Hey so sorry about this, I actually meant to post my previous message in the other issue you reported, not this one. I got confused.
The fix for this issue is already in progress.

**Comment by aldrinmathew** [comment]
The fix for this issue will land in the next release
